export type RadioContext =
  | 'proximity'
  | 'star_capture'
  | 'meteor_event'
  | 'paralyzed'
  | 'rescue'
  | 'launch'
  | 'philosophical'
  | 'hunting'
  | 'star_spawn'
  | 'asteroid_warning'
  | 'asteroid_clear'
  | 'wormhole_shuffle'
  | 'supernova'
  | 'fire'
  | 'chasing';
